version: "3.1"

services:
  fl-auth:
    # build: ../../fl-auth/
    image: ghcr.io/jamestiberiuskirk/fl-auth
    environment:
      MS_NAME: "fl-auth"
      DB_HOST: "docker_mongo_1"
        #DB_HOST: "192.168.0.100"
      DB_PORT: "27017"
      DB_NAME: "fl-auth"
      DB_USER: "fl-auth"
      DB_PASSWORD: "fl-auth123"
      SERVER_PORT: "3000"
      JWT_SECRET: "[:7Wa*yZ*VSndbq6fPchJEw-.qP+;?"

  fl-tracking-points:
    # build: ../../fl-tracking-points/
    image: ghcr.io/jamestiberiuskirk/fl-tracking-points:latest
    environment:
      MS_NAME: "fl-tracking-points"
      DB_HOST: "docker_mongo_1"
        #DB_HOST: "192.168.0.100"
      DB_PORT: "27017"
      DB_NAME: "fl-tracking-points"
      DB_USER: "fl-tracking-points"
      DB_PASSWORD: "fl-tracking-points123"
      SERVER_PORT: "3000"
      JWT_SECRET: "[:7Wa*yZ*VSndbq6fPchJEw-.qP+;?"

  fl-proxy:
    build: ./fl-proxy
    ports:
      - "80:80"
    depends_on:
      - fl-auth
      - fl-tracking-points
    restart: always