# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: FL Shared Publish

on:
  push:
    branches: [ master ]

env:
  working-dir: ./fitness-logger/fl-shared/

defaults:
  run:
    working-directory: ./fitness-logger/fl-shared/

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15

      - run: npm install
      - run: npm run ci:test
      - run: npm run build

  publish-gpr:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15
          registry-url: https://npm.pkg.github.com/

      - run: npm install
      - run: npm run ci:test
      - run: npm run build
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.TOKEN}}
